In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import warnings

warnings.filterwarnings(action = 'ignore')

In [23]:
raw_df = pd.read_excel("../data/FINAL_NUM_1029.xlsx")
raw_df

,DONG_CODE,SI_DO,GU,DONG,ACADEMY_NUM,KINDER_NUM,FIRE_NUM,ELE_SCH_NUM,MID_SCH_NUM,HIGH_SCH_NUM,CCTV_NUM,POLICE_NUM,BIKE_NUM,CAR_SHR_NUM,BUS_NUM,SUBWAY_NUM,SAFE_DLVR_NUM,DPTM_NUM,ANI_HSPT_NUM,PHARM_NUM,LEISURE_NUM,KIDS_NUM,HOSPITAL_NUM,SPORT_NUM,GYM_NUM,GOLF_NUM,STARBUCKS_NUM,MC_NUM,CON_NUM,NOISE_VIBRATION_NUM,CHILD_MED_NUM,CAFE_NUM,STD_DAY,PARK_NUM,RETAIL_NUM
0,1147010100,서울특별시,양천구,신정동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,5
1,1150010100,서울특별시,강서구,염창동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,2
2,1150010400,서울특별시,강서구,가양동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,3
3,1150010200,서울특별시,강서구,등촌동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,1
4,1150010300,서울특별시,강서구,화곡동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,1123010700,서울특별시,동대문구,청량리동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,1
463,1123010800,서울특별시,동대문구,회기동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,2
464,1123010900,서울특별시,동대문구,휘경동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,1
465,1123011000,서울특별시,동대문구,이문동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,4
466,1126010100,서울특별시,중랑구,면목동,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2022-11-01,0,4

In [5]:
df = pd.read_excel('../data/HOSPITAL_DM.xlsx',sheet_name='워크시트 익스포트')
pd.set_option('display.max_columns',30)
df

,HOSPITAL_CODE,HOSPITAL_NAME,HOSPITAL_TYPE,ADD_STR,DONG,DONG_CODE,GU_CODE,GU,STD_DAY,START_MON,START_TUE,START_WED,START_TUR,START_FRI,START_SAT,START_SUN,START_HOL,END_MON,END_TUE,END_WED,END_TUR,END_FRI,END_SAT,END_SUN,END_HOL,CATE_CODE,LAT,LON,SI_DO,SI_DO_CODE
0,1115,김치과의원,치과의원,서울특별시 송파구 동남로 102,문정동,1171010800,11240,송파구,2022-10-27,1000,1000,1000,1400,1000,1000,930,1000,1800,1800,1800,2000,1800,1600,1300,1300,D111,37.489414,127.122764,서울특별시,11
1,182,서울포레스트정신건강의학과의원,의원,서울특별시 강남구 도산대로 420,청담동,1168010400,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,1000,930,900,2000,2000,2000,2000,2000,1600,1400,1330,D111,37.523055,127.042083,서울특별시,11
2,439,강남성모내과의원,의원,서울특별시 강남구 개포로 615,개포동,1168010300,11230,강남구,2022-10-27,830,830,830,830,830,830,830,1000,1800,1800,1800,1800,1800,1400,1330,1500,D111,37.492659,127.075586,서울특별시,11
3,487,속편한한의원,한의원,서울특별시 강남구 개포로 233,개포동,1168010300,11230,강남구,2022-10-27,900,900,900,900,900,900,900,900,1800,2000,1800,2000,1800,1400,1200,1800,D111,37.479028,127.048118,서울특별시,11
4,651,유브의원,의원,서울특별시 강남구 봉은사로 457,삼성동,1168010500,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,1000,1000,830,1900,1900,1900,1900,1900,1400,1430,1500,D111,37.512212,127.049500,서울특별시,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18682,14833,세련치과의원,치과의원,서울특별시 은평구 은평로 23,신사동,1138010900,11120,은평구,2022-10-27,1000,930,930,930,930,930,1000,1000,1800,1830,1830,2030,1830,1530,1400,1300,D111,37.598166,126.910402,서울특별시,11
18683,14846,꿈나무가정의원,의원,서울특별시 은평구 갈현로 14,신사동,1138010900,11120,은평구,2022-10-27,900,900,900,900,900,900,900,900,1830,1830,1830,1830,1830,1400,1300,1300,D111,37.599107,126.910446,서울특별시,11
18684,14951,동서의원,의원,서울특별시 은평구 통일로 735,대조동,1138010600,11120,은평구,2022-10-27,900,900,900,900,900,900,900,900,1800,1800,1800,1800,1800,1300,1800,1800,D111,37.611117,126.929074,서울특별시,11
18685,15496,윤안과의원,의원,서울특별시 강남구 선릉로 328,대치동,1168010600,11230,강남구,2022-10-27,1000,1000,1000,1400,1000,1000,1000,900,1800,1800,1800,1800,1800,1200,1300,1400,D111,37.498979,127.051913,서울특별시,11
18686,16287,경희진평한의원,한의원,서울특별시 강남구 테헤란로 333,역삼동,1168010100,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,930,1200,930,2000,2000,1900,2000,2000,1300,1700,1600,D111,37.504697,127.048013,서울특별시,11

In [6]:
df = df[~df['HOSPITAL_NAME'].str.contains('성형')] # 성형외과 제거
df.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            18674, 18675, 18676, 18678, 18680, 18682, 18683, 18684, 18685,
            18686],
           dtype='int64', length=18017)

In [7]:
tmp_df = df[['HOSPITAL_CODE','HOSPITAL_NAME','HOSPITAL_TYPE','ADD_STR','DONG','DONG_CODE']]
tmp_df

,HOSPITAL_CODE,HOSPITAL_NAME,HOSPITAL_TYPE,ADD_STR,DONG,DONG_CODE
0,1115,김치과의원,치과의원,서울특별시 송파구 동남로 102,문정동,1171010800
1,182,서울포레스트정신건강의학과의원,의원,서울특별시 강남구 도산대로 420,청담동,1168010400
2,439,강남성모내과의원,의원,서울특별시 강남구 개포로 615,개포동,1168010300
3,487,속편한한의원,한의원,서울특별시 강남구 개포로 233,개포동,1168010300
4,651,유브의원,의원,서울특별시 강남구 봉은사로 457,삼성동,1168010500
...,...,...,...,...,...,...
18682,14833,세련치과의원,치과의원,서울특별시 은평구 은평로 23,신사동,1138010900
18683,14846,꿈나무가정의원,의원,서울특별시 은평구 갈현로 14,신사동,1138010900
18684,14951,동서의원,의원,서울특별시 은평구 통일로 735,대조동,1138010600
18685,15496,윤안과의원,의원,서울특별시 강남구 선릉로 328,대치동,1168010600
18686,16287,경희진평한의원,한의원,서울특별시 강남구 테헤란로 333,역삼동,1168010100

In [8]:
std = pd.read_excel('../data/한국행정구역분류_2022.10.1.기준_20221006123917.xlsx',sheet_name='행정동 및 법정동코드와의 연계표')
std.columns = std.loc[0]
std = std[1:]
std_seoul = std[std['시도'] == '서울특별시']
std_df = std_seoul[['시군구','행정동\n(행정기관명)','법정동','행정기관코드','법정동코드','법정동 관할구역\n분할여부']][1:]
std_df.columns = ['시군구','행정동','법정동','행정기관코드','법정동코드','분할여부']
std_df

     시군구    행정동  법정동      행정기관코드       법정동코드  분할여부
2    종로구    종로구  종로구  1111000000  1111000000   NaN
3    종로구  청운효자동  청운동  1111051500  1111010100   NaN
4    종로구  청운효자동  신교동  1111051500  1111010200   NaN
5    종로구  청운효자동  궁정동  1111051500  1111010300   NaN
6    종로구  청운효자동  효자동  1111051500  1111010400   NaN
..   ...    ...  ...         ...         ...   ...
763  강동구  성내제2동  성내동  1174065000  1174010800  분할연계
764  강동구  성내제3동  성내동  1174066000  1174010800  분할연계
765  강동구     길동   길동  1174068500  1174010500   NaN
766  강동구  둔촌제1동  둔촌동  1174069000  1174010600  분할연계
767  강동구  둔촌제2동  둔촌동  1174070000  1174010600  분할연계

[766 rows x 6 columns]

In [9]:
data = tmp_df['DONG_CODE'].value_counts()

In [10]:
x = pd.DataFrame(data)
x.rename(columns={'DONG_CODE':'HOSPITAL_NUM'},inplace=True)
x['DONG_CODE'] = x.index
x.index = range(len(x))
x

     HOSPITAL_NUM   DONG_CODE
0             578  1165010800
1             510  1168010100
2             468  1168010700
3             394  1135010500
4             376  1168010800
..            ...         ...
397             1  1156011900
398             1  1114013900
399             1  1111016500
400             1  1114017400
401             1  1129011700

[402 rows x 2 columns]

In [11]:
df = pd.read_csv('../data/법정동_1029.csv')
pd.set_option('display.max_columns',33)
df.rename(columns={'Unnamed: 0':'index'},inplace=True)
df.set_index('index',inplace=True)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28

In [12]:
copy_df = df.copy()

In [13]:
merge = pd.merge(copy_df,x, how='outer',on='DONG_CODE')
pd.set_option('display.max_columns',35)
merge

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM_x,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM_y
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,NaN
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,NaN
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,NaN
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [14]:
df = merge.fillna(0)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM_x,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM_y
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,0.0
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,0.0
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,0.0
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [15]:
del(df['HOSPITAL_NUM_x'])

In [16]:
df.rename(columns={'HOSPITAL_NUM_y':'HOSPITAL_NUM'},inplace=True)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,0.0
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,0.0
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,0.0
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [17]:
def dong_change(df):
    sample_df = df
    sample_df.drop('STD_DAY',axis=1,inplace=True)

    change_df = pd.read_excel('행정구역분류.xlsx',header=1)

    seoul_df = change_df[change_df['시도']=='서울특별시']
    seoul_df = seoul_df[seoul_df['행정구역명'].str[-1] =='동']
    seoul_df = seoul_df[['시군구','행정구역명','법정동','법정동코드','행정기관코드','법정동 관할구역\n분할여부']]
    seoul_df.columns = ['GU','DONG','법정동','DONG_CODE','행정기관코드','분할여부']
    non_div = seoul_df[seoul_df['분할여부'].isnull()][['GU','DONG','DONG_CODE','행정기관코드']]

    remove_du = non_div.drop_duplicates(['행정기관코드'])

    tmp_sample_df = sample_df.drop(['GU','DONG'],axis=1)
    con_df1 = pd.merge(tmp_sample_df,non_div,on="DONG_CODE")

    non_div_result = con_df1.groupby('행정기관코드').sum()
    non_div_result = non_div_result.drop(['DONG_CODE'],axis=1)

    non_div_result = pd.merge(non_div_result, remove_du,right_on='행정기관코드',left_index=True)
    non_div_result.drop('DONG_CODE',inplace=True,axis=1)

    non_div_result.rename(columns = {'행정기관코드':'DONG_CODE'},inplace=True)

    div_df = seoul_df[seoul_df['분할여부']=='분할연계'][['GU','DONG','DONG_CODE','행정기관코드']]

    div_dong_count = div_df.groupby('DONG_CODE').count()[['행정기관코드']]
    div_dong_count.columns = ['DONG_COUNT']

    con_df2 = pd.merge(sample_df, div_dong_count,left_on='DONG_CODE',right_index=True)
    con_df2.set_index('DONG_CODE',inplace=True)

    con_df2 = con_df2.iloc[:,3:]
    cal_df = con_df2.div(con_df2['DONG_COUNT'], axis=0) 
    div_result_df = pd.merge(div_df,cal_df,left_on='DONG_CODE',right_index=True)
    div_result_df = div_result_df.drop(['DONG_CODE','DONG_COUNT'],axis=1)
    div_result_df.rename(columns = {'행정기관코드':'DONG_CODE'},inplace=True)

    non_div_result = non_div_result[div_result_df.columns]
    result_df = pd.concat([non_div_result, div_result_df],axis=0)
    result_sum = result_df.groupby('DONG_CODE').sum()
    
    remove_result_du =result_df.drop_duplicates(['DONG_CODE'])[['GU','DONG','DONG_CODE']]
    result_df2 = pd.merge(result_sum, remove_result_du,right_on='DONG_CODE',left_index=True)

    return result_df2

In [18]:
change_df = dong_change(df)
change_df

,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,HOSPITAL_NUM,GU,DONG,DONG_CODE
2,0.333333,0.333333,0.0,1.000000,2.000000,4.333333,18816.000000,2.000000,0.0,1.000000,0.000000,0.000000,3.0,0.0,0.000000,1.0,2.000000,0.0,4.000000,7.333333,56.666667,1.000000,39.666667,11.666667,5.666667,2.000000,18.000000,11.666667,종로구,청운효자동,1111051500
12,1.333333,7.333333,0.0,0.000000,3.000000,17.333333,22848.000000,0.000000,0.0,1.000000,10.000000,0.000000,0.0,18.0,3.000000,0.0,2.000000,0.0,20.000000,10.333333,41.666667,5.000000,100.666667,18.666667,11.666667,1.000000,19.000000,74.666667,종로구,사직동,1111053000
24,1.000000,1.000000,1.0,0.000000,1.000000,2.000000,14112.000000,1.000000,0.0,0.000000,10.000000,0.000000,1.0,3.0,0.000000,0.0,0.000000,0.0,2.000000,1.000000,22.000000,1.000000,52.000000,8.000000,7.000000,0.000000,2.000000,7.000000,종로구,삼청동,1111054000
31,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,6048.000000,1.000000,0.0,0.000000,0.000000,0.000000,1.0,2.0,2.000000,1.0,4.000000,0.0,8.000000,5.000000,41.000000,5.000000,30.000000,18.000000,5.000000,3.000000,24.000000,4.000000,종로구,부암동,1111055000
34,0.000000,1.000000,0.0,0.000000,1.000000,5.000000,4032.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,5.0,5.000000,0.0,0.000000,0.0,6.000000,10.000000,21.000000,0.000000,36.000000,25.000000,7.000000,0.000000,28.000000,14.000000,종로구,평창동,1111056000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,1442.333333,0.333333,0.0,1.666667,16.666667,0.666667,0.0,10.0,4.666667,1.0,1.333333,0.0,38.666667,4.000000,52.000000,6.666667,47.666667,11.000000,6.000000,2.666667,63.333333,59.333333,강동구,성내2동,1174065000
763,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,1442.333333,0.333333,0.0,1.666667,16.666667,0.666667,0.0,10.0,4.666667,1.0,1.333333,0.0,38.666667,4.000000,52.000000,6.666667,47.666667,11.000000,6.000000,2.666667,63.333333,59.333333,강동구,성내3동,1174066000
764,1.000000,2.000000,0.0,1.000000,0.000000,35.000000,4327.000000,1.000000,0.0,3.000000,20.000000,1.000000,0.0,18.0,9.000000,1.0,6.000000,0.0,76.000000,10.000000,119.000000,10.000000,63.000000,22.000000,9.000000,8.000000,100.000000,120.000000,강동구,길동,1174068500
765,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,2163.500000,1.500000,0.5,0.000000,0.000000,0.000000,1.0,4.0,3.000000,0.0,2.000000,0.0,17.000000,0.000000,32.500000,2.000000,17.500000,7.000000,5.500000,1.500000,38.000000,14.500000,강동구,둔촌1동,1174069000
766,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,2163.500000,1.500000,0.5,0.000000,0.000000,0.000000,1.0,4.0,3.000000,0.0,2.000000,0.0,17.000000,0.000000,32.500000,2.000000,17.500000,7.000000,5.500000,1.500000,38.000000,14.500000,강동구,둔촌2동,1174070000

In [19]:
def add_bus_data(df):
    df.drop('BUS_NUM',axis=1,inplace=True)
    copy_df = df.copy()
    copy_df['GU_DONG'] = copy_df['GU'] + copy_df['DONG']
    
    bus_df = pd.read_csv('동별_버스정보_수정.csv')
    merge_df = pd.merge(copy_df, bus_df)
    merge_df.drop('GU_DONG',axis=1,inplace=True)
    
    return merge_df

In [20]:
final_df = add_bus_data(change_df)
final_df

,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,HOSPITAL_NUM,GU,DONG,DONG_CODE,BUS_CNT
0,0.333333,0.333333,0.0,1.000000,2.000000,4.333333,18816.000000,2.000000,0.0,1.000000,0.000000,0.000000,3.0,0.0,0.000000,1.0,2.000000,0.0,4.000000,7.333333,56.666667,1.000000,39.666667,5.666667,2.000000,18.000000,11.666667,종로구,청운효자동,1111051500,14.0
1,1.333333,7.333333,0.0,0.000000,3.000000,17.333333,22848.000000,0.000000,0.0,1.000000,10.000000,0.000000,0.0,18.0,3.000000,0.0,2.000000,0.0,20.000000,10.333333,41.666667,5.000000,100.666667,11.666667,1.000000,19.000000,74.666667,종로구,사직동,1111053000,16.0
2,1.000000,1.000000,1.0,0.000000,1.000000,2.000000,14112.000000,1.000000,0.0,0.000000,10.000000,0.000000,1.0,3.0,0.000000,0.0,0.000000,0.0,2.000000,1.000000,22.000000,1.000000,52.000000,7.000000,0.000000,2.000000,7.000000,종로구,삼청동,1111054000,11.0
3,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,6048.000000,1.000000,0.0,0.000000,0.000000,0.000000,1.0,2.0,2.000000,1.0,4.000000,0.0,8.000000,5.000000,41.000000,5.000000,30.000000,5.000000,3.000000,24.000000,4.000000,종로구,부암동,1111055000,9.0
4,0.000000,1.000000,0.0,0.000000,1.000000,5.000000,4032.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,5.0,5.000000,0.0,0.000000,0.0,6.000000,10.000000,21.000000,0.000000,36.000000,7.000000,0.000000,28.000000,14.000000,종로구,평창동,1111056000,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,1442.333333,0.333333,0.0,1.666667,16.666667,0.666667,0.0,10.0,4.666667,1.0,1.333333,0.0,38.666667,4.000000,52.000000,6.666667,47.666667,6.000000,2.666667,63.333333,59.333333,강동구,성내2동,1174065000,11.0
422,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,1442.333333,0.333333,0.0,1.666667,16.666667,0.666667,0.0,10.0,4.666667,1.0,1.333333,0.0,38.666667,4.000000,52.000000,6.666667,47.666667,6.000000,2.666667,63.333333,59.333333,강동구,성내3동,1174066000,9.0
423,1.000000,2.000000,0.0,1.000000,0.000000,35.000000,4327.000000,1.000000,0.0,3.000000,20.000000,1.000000,0.0,18.0,9.000000,1.0,6.000000,0.0,76.000000,10.000000,119.000000,10.000000,63.000000,9.000000,8.000000,100.000000,120.000000,강동구,길동,1174068500,28.0
424,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,2163.500000,1.500000,0.5,0.000000,0.000000,0.000000,1.0,4.0,3.000000,0.0,2.000000,0.0,17.000000,0.000000,32.500000,2.000000,17.500000,5.500000,1.500000,38.000000,14.500000,강동구,둔촌1동,1174069000,4.0
425,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,2163.500000,1.500000,0.5,0.000000,0.000000,0.000000,1.0,4.0,3.000000,0.0,2.000000,0.0,17.000000,0.000000,32.500000,2.000000,17.500000,5.500000,1.500000,38.000000,14.500000,강동구,둔촌2동,1174070000,20.0

In [21]:
final_df[['HOSPITAL_NUM']].describe()

       HOSPITAL_NUM
count    426.000000
mean      42.293427
std       35.024099
min        1.000000
25%       23.500000
50%       34.500000
75%       48.000000
max      255.000000

In [22]:
final_df.to_csv('성형외과제거_및_버스수정_행정동_변환_1101.csv',mode='w')