In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('../data/서울시 도시계획 정비사업 현황.csv',encoding='cp949')
df

,조서관리코드,프로젝트코드,지자체,조서유형(구분),대분류,중분류,소분류,위치명,지역명,면적기정,면적증감코드,면적변경,면적변경후,결정고시관리코드
0,11000AGZ201809140069,11000PPL201808020005,서울특별시,변경,의제처리구역,정비구역,주택재개발사업구역,신림동 808 일대,신림1재정비촉진구역,233729.0,2.0,8955.5,224773.5,11000NTC201808020005
1,11000AGZ201809140142,11000PPL201801180002,서울특별시,폐지,의제처리구역,정비구역,주거환경개선사업,종로구 창신동 143-27,종로구 창신동 143-27번지 일대 주거환경개선사업 정비예정구역,4000.0,NaN,4000.0,NaN,11000NTC201801180002
2,11000AGZ196601183682,11000PPL196601180242,서울특별시,신설,의제처리구역,정비구역,도시환경정비사업지구,옥수동 및 신당동,신당지구,0.0,NaN,NaN,393000.0,11000NTC196601180242
3,11000AGZ196601183683,11000PPL196601180242,서울특별시,신설,의제처리구역,정비구역,도시환경정비사업지구,해방촌,용산지구,0.0,NaN,NaN,106250.0,11000NTC196601180242
4,11000AGZ196601183684,11000PPL196601180242,서울특별시,신설,의제처리구역,정비구역,도시환경정비사업지구,한남동~보광동,한남지구,0.0,NaN,NaN,132300.0,11000NTC196601180242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5955,11110AGZ202202030024,11110PPL202202030004,종로구,신설,의제처리구역,정비구역,도시환경정비사업구역,종로구 창신동 328-18번지,창신4도시정비형 재개발구역 4-3,0.0,NaN,NaN,5742.0,11110NTC202202030004
5956,11110AGZ202202030025,11110PPL202202030004,종로구,변경,의제처리구역,정비구역,도시환경정비사업구역,NaN,창신 도시정비형 재개발구역,11509.0,NaN,NaN,107997.5,11110NTC202202030004
5957,11200AGZ202205240001,11200PPL202205240002,성동구,변경,의제처리구역,정비구역,주택재건축사업,응봉동 193-162번지 일대,응봉1주택재건축 정비사업,39642.0,NaN,NaN,39465.2,11200NTC202205240002
5958,11000AGZ202206020001,11000PPL202206020001,서울특별시,변경,의제처리구역,정비구역,주택재건축사업,강북구 미아동 3-111번지 일대,미아동 3-111번지 일대 주택재건축정비사업,10335.0,NaN,NaN,10288.8,11305NTC202206020001
5959,11215AGZ202205030001,11215PPL202205030007,광진구,신설,의제처리구역,정비구역,재건축사업구역,광진구 중곡4동 18-24번지 일대,신향빌라 재건축사업,0.0,NaN,NaN,15757.8,11000NTC202206070005

In [10]:
area = df[['위치명']]
area

                      위치명
0              신림동 808 일대
1          종로구 창신동 143-27
2               옥수동 및 신당동
3                     해방촌
4                 한남동~보광동
...                   ...
5955     종로구 창신동 328-18번지
5956                  NaN
5957     응봉동 193-162번지 일대
5958   강북구 미아동 3-111번지 일대
5959  광진구 중곡4동 18-24번지 일대

[5960 rows x 1 columns]

In [18]:
area = area.fillna('모름')

In [20]:
area[area['위치명'].str.contains('무악')]

                                    위치명
859                      종로구 무악동 7번지 일대
2233  서울특별시 종로구 무악동 45 46번지 일대 (1103필지)
2237                         종로구 무악동 46
3172                     종로구 무악동 46번지일대
3177      서울 종로구 무악동 45 46번지 일대(1111필지)
3291                   서울 종로구 무악동 46 일대
3719                       종로구 무악동 46일대
3855                   종로구 무악동 46 번지 일대
4094                    종로구 무악동 46번지 일대
4569                   종로구 무악동 46번지 일대
5406                    종로구 무악동 46번지 일대
5862                   종로구 무악동 46번지 일대

In [21]:
area[area['위치명'].str.contains('후암')]

                         위치명
380      용산구 후암동 산1-114번지 일대
381       용산구 후암동 101-6번지 일대
826       용산구 후암동 산1 401번지일대
862          용산구 후암동 44번지 일대
1723  서울특별시 용산구 후암동 400번지 일원
1802        용산구 후암동 406번지 일원
1817           용산구 후암동 400일대
1825     서울시 용산구 후암동 400번지일대
2213          용산구 후암동 406 일대

In [22]:
area[area['위치명'].str.contains('원효')]

                                위치명
69                    용산구 원효3가 50-1
2745   용산구 용문동 90번지 및  원효로3가 1번지 일대
2746   용산구 용문동 90번지 및  원효로3가 1번지 일대
2747    용산구 용문동 90번지 및 원효로3가 1번지 일대
3786    용산구 용문동 90번지 및 원효로3가 1번지 일대
4028    용산구 용문동 90번지 및 원효로3가 1번지 일대
4860     용산구 용문동 90번지 및 원효로3가1번지 일대
5769  용산구 용문동 90번지  및 원효로 3가 1번지 일대

In [23]:
area[area['위치명'].str.contains('이태원')]

                       위치명
376       용산구 이태원 260번지 일대
498        용산구 이태원동 260 일대
825   용산구 이태원동 258 261번지일대
1091      용산구 이태원 258번지 일대
2779         이태원1동 77번지 일대
2868       용산구 이태원동 225 일대
4756       용산구 이태원동 225 일대
4777      용산구 이태원2동 260 일대
4819     용산구 이태원1동 77번지 일대
4932     용산구 이태원1동 77번지 일대
5053     용산구 이태원1동 77번지 일대
5699         용산구 이태원2동 260