In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings(action = 'ignore')

In [2]:
df = pd.read_excel('../data/HOSPITAL_DM.xlsx',sheet_name='워크시트 익스포트')

In [3]:
pd.set_option('display.max_columns',30)

In [4]:
df

,HOSPITAL_CODE,HOSPITAL_NAME,HOSPITAL_TYPE,ADD_STR,DONG,DONG_CODE,GU_CODE,GU,STD_DAY,START_MON,START_TUE,START_WED,START_TUR,START_FRI,START_SAT,START_SUN,START_HOL,END_MON,END_TUE,END_WED,END_TUR,END_FRI,END_SAT,END_SUN,END_HOL,CATE_CODE,LAT,LON,SI_DO,SI_DO_CODE
0,1115,김치과의원,치과의원,서울특별시 송파구 동남로 102,문정동,1171010800,11240,송파구,2022-10-27,1000,1000,1000,1400,1000,1000,930,1000,1800,1800,1800,2000,1800,1600,1300,1300,D111,37.489414,127.122764,서울특별시,11
1,182,서울포레스트정신건강의학과의원,의원,서울특별시 강남구 도산대로 420,청담동,1168010400,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,1000,930,900,2000,2000,2000,2000,2000,1600,1400,1330,D111,37.523055,127.042083,서울특별시,11
2,439,강남성모내과의원,의원,서울특별시 강남구 개포로 615,개포동,1168010300,11230,강남구,2022-10-27,830,830,830,830,830,830,830,1000,1800,1800,1800,1800,1800,1400,1330,1500,D111,37.492659,127.075586,서울특별시,11
3,487,속편한한의원,한의원,서울특별시 강남구 개포로 233,개포동,1168010300,11230,강남구,2022-10-27,900,900,900,900,900,900,900,900,1800,2000,1800,2000,1800,1400,1200,1800,D111,37.479028,127.048118,서울특별시,11
4,651,유브의원,의원,서울특별시 강남구 봉은사로 457,삼성동,1168010500,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,1000,1000,830,1900,1900,1900,1900,1900,1400,1430,1500,D111,37.512212,127.049500,서울특별시,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18682,14833,세련치과의원,치과의원,서울특별시 은평구 은평로 23,신사동,1138010900,11120,은평구,2022-10-27,1000,930,930,930,930,930,1000,1000,1800,1830,1830,2030,1830,1530,1400,1300,D111,37.598166,126.910402,서울특별시,11
18683,14846,꿈나무가정의원,의원,서울특별시 은평구 갈현로 14,신사동,1138010900,11120,은평구,2022-10-27,900,900,900,900,900,900,900,900,1830,1830,1830,1830,1830,1400,1300,1300,D111,37.599107,126.910446,서울특별시,11
18684,14951,동서의원,의원,서울특별시 은평구 통일로 735,대조동,1138010600,11120,은평구,2022-10-27,900,900,900,900,900,900,900,900,1800,1800,1800,1800,1800,1300,1800,1800,D111,37.611117,126.929074,서울특별시,11
18685,15496,윤안과의원,의원,서울특별시 강남구 선릉로 328,대치동,1168010600,11230,강남구,2022-10-27,1000,1000,1000,1400,1000,1000,1000,900,1800,1800,1800,1800,1800,1200,1300,1400,D111,37.498979,127.051913,서울특별시,11
18686,16287,경희진평한의원,한의원,서울특별시 강남구 테헤란로 333,역삼동,1168010100,11230,강남구,2022-10-27,1000,1000,1000,1000,1000,930,1200,930,2000,2000,1900,2000,2000,1300,1700,1600,D111,37.504697,127.048013,서울특별시,11

In [5]:
df = df[~df['HOSPITAL_NAME'].str.contains('성형')] # 성형외과 제거
df.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            18674, 18675, 18676, 18678, 18680, 18682, 18683, 18684, 18685,
            18686],
           dtype='int64', length=18017)

In [6]:
tmp_df = df[['HOSPITAL_CODE','HOSPITAL_NAME','HOSPITAL_TYPE','ADD_STR','DONG','DONG_CODE']]
tmp_df

,HOSPITAL_CODE,HOSPITAL_NAME,HOSPITAL_TYPE,ADD_STR,DONG,DONG_CODE
0,1115,김치과의원,치과의원,서울특별시 송파구 동남로 102,문정동,1171010800
1,182,서울포레스트정신건강의학과의원,의원,서울특별시 강남구 도산대로 420,청담동,1168010400
2,439,강남성모내과의원,의원,서울특별시 강남구 개포로 615,개포동,1168010300
3,487,속편한한의원,한의원,서울특별시 강남구 개포로 233,개포동,1168010300
4,651,유브의원,의원,서울특별시 강남구 봉은사로 457,삼성동,1168010500
...,...,...,...,...,...,...
18682,14833,세련치과의원,치과의원,서울특별시 은평구 은평로 23,신사동,1138010900
18683,14846,꿈나무가정의원,의원,서울특별시 은평구 갈현로 14,신사동,1138010900
18684,14951,동서의원,의원,서울특별시 은평구 통일로 735,대조동,1138010600
18685,15496,윤안과의원,의원,서울특별시 강남구 선릉로 328,대치동,1168010600
18686,16287,경희진평한의원,한의원,서울특별시 강남구 테헤란로 333,역삼동,1168010100

In [7]:
std = pd.read_excel('../data/한국행정구역분류_2022.10.1.기준_20221006123917.xlsx',sheet_name='행정동 및 법정동코드와의 연계표')
std.columns = std.loc[0]
std = std[1:]
std_seoul = std[std['시도'] == '서울특별시']
std_df = std_seoul[['시군구','행정동\n(행정기관명)','법정동','행정기관코드','법정동코드','법정동 관할구역\n분할여부']][1:]
std_df.columns = ['시군구','행정동','법정동','행정기관코드','법정동코드','분할여부']
std_df

     시군구    행정동  법정동      행정기관코드       법정동코드  분할여부
2    종로구    종로구  종로구  1111000000  1111000000   NaN
3    종로구  청운효자동  청운동  1111051500  1111010100   NaN
4    종로구  청운효자동  신교동  1111051500  1111010200   NaN
5    종로구  청운효자동  궁정동  1111051500  1111010300   NaN
6    종로구  청운효자동  효자동  1111051500  1111010400   NaN
..   ...    ...  ...         ...         ...   ...
763  강동구  성내제2동  성내동  1174065000  1174010800  분할연계
764  강동구  성내제3동  성내동  1174066000  1174010800  분할연계
765  강동구     길동   길동  1174068500  1174010500   NaN
766  강동구  둔촌제1동  둔촌동  1174069000  1174010600  분할연계
767  강동구  둔촌제2동  둔촌동  1174070000  1174010600  분할연계

[766 rows x 6 columns]

In [8]:
data = tmp_df['DONG_CODE'].value_counts()

In [9]:
x = pd.DataFrame(data)

In [10]:
x

            DONG_CODE
1165010800        578
1168010100        510
1168010700        468
1135010500        394
1168010800        376
...               ...
1156011900          1
1114013900          1
1111016500          1
1114017400          1
1129011700          1

[402 rows x 1 columns]

In [35]:
df = pd.read_csv('../data/법정동_1029.csv')
pd.set_option('display.max_columns',33)
df.rename(columns={'Unnamed: 0':'index'},inplace=True)
df.set_index('index',inplace=True)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28

In [36]:
copy_df = df.copy()

In [37]:
x.rename(columns={'DONG_CODE':'HOSPITAL_NUM'},inplace=True)

In [38]:
x['DONG_CODE'] = x.index

In [39]:
x.index = range(len(x))
x

     HOSPITAL_NUM   DONG_CODE
0             578  1165010800
1             510  1168010100
2             468  1168010700
3             394  1135010500
4             376  1168010800
..            ...         ...
397             1  1156011900
398             1  1114013900
399             1  1111016500
400             1  1114017400
401             1  1129011700

[402 rows x 2 columns]

In [40]:
copy_df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28

In [41]:
merge = pd.merge(copy_df,x, how='outer',on='DONG_CODE')

In [42]:
pd.set_option('display.max_columns',35)
merge

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM_x,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM_y
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,NaN
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,NaN
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,NaN
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [43]:
df = merge.fillna(0)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HOSPITAL_NUM_x,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM_y
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,0.0
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,2,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,0.0
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,0.0
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,3,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,90,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,199,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,180,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,120,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,29,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [44]:
del(df['HOSPITAL_NUM_x'])

In [45]:
df.rename(columns={'HOSPITAL_NUM_y':'HOSPITAL_NUM'},inplace=True)
df

,SI_DO,GU,DONG_CODE,DONG,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,NOISE_VIBRATION_NUM,MID_SCH_NUM,MC_NUM,LEISURE_NUM,KINDER_NUM,KIDS_NUM,HIGH_SCH_NUM,GYM_NUM,GOLF_NUM,FIRE_NUM,ELE_SCH_NUM,DPTM_NUM,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BUS_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,STD_DAY,HOSPITAL_NUM
0,서울특별시,종로구,1111010100,청운동,0,0,0,0,0,0,2016,1,0,0,0,0,2,0,0,0,2,0,2,0,12,0,8,3,2,0,2,2022-10-28,0.0
1,서울특별시,종로구,1111010200,신교동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,1,0,0,0,0,14,0,1,0,0,1,5,2022-10-28,2.0
2,서울특별시,종로구,1111010300,궁정동,0,0,0,0,1,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2022-10-28,0.0
3,서울특별시,종로구,1111010400,효자동,0,0,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,1,0,0,2022-10-28,0.0
4,서울특별시,종로구,1111010500,창성동,0,0,0,0,0,1,2016,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,3,1,1,0,1,2022-10-28,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,서울특별시,강동구,1174010700,암사동,1,1,0,2,1,22,4327,2,0,1,30,4,1,16,8,1,6,0,66,11,133,4,70,11,11,5,197,2022-10-28,90.0
463,서울특별시,강동구,1174010900,천호동,3,4,0,3,1,51,4327,4,1,13,70,6,1,14,7,1,6,1,136,12,266,17,131,32,15,4,124,2022-10-28,197.0
464,서울특별시,강동구,1174010800,성내동,1,4,0,2,1,38,4327,1,0,5,50,2,0,30,14,3,4,0,116,12,156,20,143,33,18,8,190,2022-10-28,178.0
465,서울특별시,강동구,1174010500,길동,1,2,0,1,0,35,4327,1,0,3,20,1,0,18,9,1,6,0,76,10,119,10,63,22,9,8,100,2022-10-28,120.0
466,서울특별시,강동구,1174010600,둔촌동,1,0,0,0,2,20,4327,3,1,0,0,0,2,8,6,0,4,0,34,0,65,4,35,14,11,3,76,2022-10-28,29.0

In [ ]:
df.to_csv('법정동데이터_병원_성형외과제거.csv',mode='w')