In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings(action='ignore')

In [2]:
df = pd.read_csv('1101_대형마트_추가.csv')
df

,index,GU,DONG,DONG_CODE,SUBWAY_NUM,STARBUCKS_NUM,SPORT_NUM,SAFE_DLVR_NUM,POLICE_NUM,PHARM_NUM,...,CON_NUM,CHILD_MED_NUM,CCTV_NUM,CAR_SHR_NUM,CAFE_NUM,BIKE_NUM,ANI_HSPT_NUM,ACADEMY_NUM,BUS_CNT,RETAIL_NUM
0,0,종로구,청운효자동,1111051500,0.333333,0.333333,0.0,1.000000,2.000000,4.333333,...,4.000000,7.333333,56.666667,1.000000,39.666667,5.666667,2.000000,18.000000,14.0,0.000000
1,1,종로구,사직동,1111053000,1.333333,7.333333,0.0,0.000000,3.000000,17.333333,...,20.000000,10.333333,41.666667,5.000000,100.666667,11.666667,1.000000,19.000000,16.0,2.000000
2,2,종로구,삼청동,1111054000,1.000000,1.000000,1.0,0.000000,1.000000,2.000000,...,2.000000,1.000000,22.000000,1.000000,52.000000,7.000000,0.000000,2.000000,11.0,0.000000
3,3,종로구,부암동,1111055000,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,...,8.000000,5.000000,41.000000,5.000000,30.000000,5.000000,3.000000,24.000000,9.0,0.000000
4,4,종로구,평창동,1111056000,0.000000,1.000000,0.0,0.000000,1.000000,5.000000,...,6.000000,10.000000,21.000000,0.000000,36.000000,7.000000,0.000000,28.000000,37.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,421,강동구,성내2동,1174065000,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,...,38.666667,4.000000,52.000000,6.666667,47.666667,6.000000,2.666667,63.333333,11.0,3.333333
422,422,강동구,성내3동,1174066000,0.333333,1.333333,0.0,0.666667,0.333333,12.666667,...,38.666667,4.000000,52.000000,6.666667,47.666667,6.000000,2.666667,63.333333,9.0,3.333333
423,423,강동구,길동,1174068500,1.000000,2.000000,0.0,1.000000,0.000000,35.000000,...,76.000000,10.000000,119.000000,10.000000,63.000000,9.000000,8.000000,100.000000,28.0,8.000000
424,424,강동구,둔촌1동,1174069000,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,...,17.000000,0.000000,32.500000,2.000000,17.500000,5.500000,1.500000,38.000000,4.0,0.000000
425,425,강동구,둔촌2동,1174070000,0.500000,0.000000,0.0,0.000000,1.000000,10.000000,...,17.000000,0.000000,32.500000,2.000000,17.500000,5.500000,1.500000,38.000000,20.0,0.000000