In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("RB_INDOOR_CLTUR_SPCE_INFO_2020.csv")
pd.set_option('display.max_columns',len(df.columns))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4217 entries, 0 to 4216
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cate_nm        4217 non-null   object
 1   entrp_nm       4216 non-null   object
 2   load_addr      4215 non-null   object
 3   city_do_cd     4197 non-null   float64
 4   city_gn_gu_cd  4197 non-null   float64
 5   xpos_lo        4177 non-null   float64
 6   ypos_la        4177 non-null   float64
 7   area_nm        4216 non-null   object
 8   homepage_url   1081 non-null   object
 9   tel_no         1189 non-null   object
 10  base_ymd       4217 non-null   object
dtypes: float64(4), object(7)
memory usage: 362.5+ KB

In [3]:
df.head()

,cate_nm,entrp_nm,load_addr,city_do_cd,city_gn_gu_cd,xpos_lo,ypos_la,area_nm,homepage_url,tel_no,base_ymd
0,오락실,빙고게임장,강원도 강릉시 강릉대로 269 2층 (교동),42.0,42150.0,128.898767,37.761699,강원,NaN,NaN,2020-12-31
1,오락실,세븐게임장,강원도 강릉시 강릉대로 272 1층 (교동),42.0,42150.0,128.899151,37.761524,강원,NaN,NaN,2020-12-31
2,오락실,FRIENDS,강원도 강릉시 강릉대로 422-7 (포남동),42.0,42150.0,128.910967,37.770876,강원,NaN,NaN,2020-12-31
3,오락실,푸쉬푸쉬,강원도 강릉시 경강로 2076 (임당동),42.0,42150.0,128.894502,37.753406,강원,NaN,NaN,2020-12-31
4,오락실,맥스라이더,강원도 강릉시 경강로 2120 (옥천동 씨네몰 6층 623호 625호),42.0,42150.0,128.898770,37.755391,강원,NaN,NaN,2020-12-31

In [4]:
df['load_addr'].str.contains('서울특별시')

0       False
1       False
2       False
3       False
4       False
        ...
4212    False
4213    False
4214     True
4215    False
4216    False
Name: load_addr, Length: 4217, dtype: object

In [5]:
condition = df['load_addr'].str.contains('서울특별시').fillna(False)
condition

0       False
1       False
2       False
3       False
4       False
        ...
4212    False
4213    False
4214     True
4215    False
4216    False
Name: load_addr, Length: 4217, dtype: bool

In [6]:
condition.unique()

array([False,  True])

In [7]:
df = df[df['load_addr'].str.contains('서울특별시').fillna(False)]
df

,cate_nm,entrp_nm,load_addr,city_do_cd,city_gn_gu_cd,xpos_lo,ypos_la,area_nm,homepage_url,tel_no,base_ymd
2541,볼링장,라인볼링장,서울특별시 강남구 강남대로 308 랜드마크타워 지하2층,11.0,11680.0,127.031739,37.490641,서울,_,02-555-4199,2020-12-31
2542,VR테마파크,VR스테이션,서울특별시 강남구 강남대로 364 미왕빌딩 지하1층~3층,11.0,11680.0,127.029335,37.495559,서울,"http://h-vrstation.com, http://www.instagram.c...",1877-8870,2020-12-31
2543,오락실,못된 강아지,서울특별시 강남구 강남대로102길 15 1층 (역삼동),11.0,11680.0,127.026998,37.502225,서울,NaN,NaN,2020-12-31
2544,VR테마파크,BAD VR 논현점,서울특별시 강남구 강남대로118길 15,11.0,11680.0,127.024710,37.506793,서울,https://blog.naver.com/jaemigym,02-6952-0313,2020-12-31
2545,VR테마파크,콩 VR 강남역점,서울특별시 강남구 강남대로94길 10 케이스퀘어강남 지하1층 콩VR,11.0,11680.0,127.028202,37.499208,서울,"http://kong-vr.com, http://www.instagram.com/k...",070-4231-5445,2020-12-31
...,...,...,...,...,...,...,...,...,...,...,...
4179,수영장,국가대표 어린이수영클럽,"서울특별시 양천구 목동동로 150, 목동 블루스퀘어 지하1층 (신정동)",11.0,11470.0,NaN,NaN,서울,NaN,263463200,2020.12.31
4181,수영장,리틀마린,"서울특별시 노원구 중계로 230, 제1상가동 지하층 101호 (중계동, 중계5단지주...",11.0,11350.0,NaN,NaN,서울,NaN,269523944,2020.12.31
4195,수영장,(주)슈퍼스타시그니쳐,"서울특별시 강서구 마곡중앙로 59-17, 류마타워2 지층 B101~B109호 (마곡동)",11.0,11500.0,NaN,NaN,서울,NaN,269492131,2020.12.31
4208,수영장,블루오션 키즈 스위밍,"서울특별시 노원구 월계로45길 21, 상가동 지하1층 (월계동, 롯데캐슬루나아파트)",11.0,11350.0,NaN,NaN,서울,NaN,29087708,2020.12.31
4214,수영장,(주)슈퍼스타스위밍아카데미마곡,"서울특별시 강서구 마곡중앙로 59-17, 류마타워2 지하1층 B110~B117호 (...",11.0,11500.0,NaN,NaN,서울,NaN,269492121,2020.12.31

In [8]:
df['cate_nm'].unique()

array(['볼링장', 'VR테마파크', '오락실', '수영장'], dtype=object)

In [9]:
df.to_csv("Leisure_in_Seoul.csv", mode='w')